import { Link } from "react-router-dom";

const PrivacyData = () => {

    const privacyPolicyData = [
        {
            title: "Introduction",
            description: "This Privacy Policy outlines how FitClue ('we,' 'us,' or 'our') collects, uses, shares, and protects user data. By using FitClue, you agree to the practices described in this policy."
        },
        {
            title: "Data Collection",
            description: (
                <div>
                    FitClue collects the following categories of data:
                    <ul className='list-unstyled'>
                        <li>
                            - Email Account Information: The email address provided during account registration is securely stored in the platform's database (via Appwrite). It may also be saved locally in the browser's local storage, along with a unique user ID generated by Appwrite. This enables session persistence and enhances user experience.
                        </li>
                        <li>
                            - Username: The chosen username is stored and may be visible to other users on the platform.
                        </li>
                        <li>
                            - Content Shared: This includes any text, comments, or links posted or shared by the user on the platform. Such content is retained and may remain visible to other users following account deletion.
                        </li>
                        <li>
                            - Technical Data: IP address and usage logs are collected by Appwrite on behalf of FitClue. This data is accessible to FitClue and is primarily used for debugging, security monitoring, and overall platform maintenance.
                        </li>
                    </ul>
                </div>
            )
        },
        {
            title: "Data Usage",
            description:
                <div>
                    The data we collect is used to:
                    <ul className='list-unstyled'>
                        <li>- Facilitate account creation.</li>
                        <li>- Display content and enable interactions within the platform.</li>
                        <li>- To help ensure a safe environment, we use automated tools to screen user-submitted content (including comments and links) for violations of our <Link to='/tos' target='_blank'>Terms of Service</Link> and <Link to='/community-guidelines' target='_blank'>Community Guidelines</Link>. If content is deemed to violate our policies, it is not submitted to the platform and is not stored by us. No record of the user or the attempted submission is retained.</li>
                        <li>- Improve platform functionality and user experience.</li>
                    </ul>
                </div>
        },
        {
            title: "Data Sharing",
            description: (
                <div>
                    FitClue does not sell or rent user data to third parties. However, data may be shared in the following instances:
                    <ul className='list-unstyled'>
                        <li>
                            - Service Providers: We rely on Appwrite to provide backend infrastructure and database services. Appwrite processes and stores user data (including IP addresses) on our behalf. All data is stored securely within Appwrite's infrastructure.
                        </li>
                        <li>
                            - AI-Powered Features: We use the Google Gemini API, a third-party AI service, to screen user-submitted content in real-time. When you attempt to submit a comment or link, the content is sent to Google's API for a safety check. If the content is flagged by the API as potentially violating our policies, it is rejected and never posted to the platform. We do not store a copy of the rejected content or any data associated with that specific submission. This process helps us prevent harmful content from appearing on the platform while minimizing the data we retain. Please note that Google's policies govern their handling of any data sent to them for this purpose.
                        </li>
                        <li>
                            - Legal Requirements: If required by law, we may disclose user data to comply with legal processes.
                        </li>
                        <li>
                            - Platform Integrity: In cases of reported content or account violations, data may be reviewed internally for resolution.
                        </li>
                    </ul>
                </div>
            )
        },
        {
            title: "Data Storage and Security",
            description:
                <div>
                    Your data is stored on servers managed by Appwrite. While we strive to protect your information, FitClue is a personal project and does not implement advanced security measures such as end-to-end encryption or multi-factor authentication. Users are encouraged to:
                    <ul className='list-unstyled'>
                        <li>- Use strong passwords for their accounts.</li>
                        <li>- Avoid sharing sensitive or personal information on the platform. </li>
                    </ul>
                </div>
        },
        {
            title: "User Rights",
            description:
                <div>
                    Users have the right to:
                    <ul className='list-unstyled'>
                        <li>- Request correction of their data.</li>
                        <li>- Report privacy violations using the 'Privacy Violation' category in the Community Guidelines.</li>
                    </ul>
                </div>
        },
        {
            title: "Cookies and Tracking",
            description: `
      FitClue may use cookies, local storage, or similar technologies to enhance functionality. These are used solely for session management and do not track users outside the platform.
    `
        },
        {
            title: "Children\'s Privacy",
            description: `
      FitClue is not intended for users under the age of 18. We do not knowingly collect personal data from children. If we become aware that such data has been collected, we will delete it promptly.
    `
        },
        {
            title: "Updates to This Policy",
            description: `
      This Privacy Policy may be updated periodically. Users will be notified of changes through platform announcements. Continued use of FitClue after updates constitutes acceptance of the revised policy.
    `
        },
        {
            title: "Contact Information",
            description: `
      For questions or concerns about this Privacy Policy, please contact us at: FitClue@altmails.com.
    `
        }
    ];

    return { privacyPolicyData };
}

export default PrivacyData;