import { Link } from "react-router-dom";

const PrivacyData = () => {

    const privacyPolicyData = [
        {
            title: "Introduction",
            description: "This Privacy Policy outlines how FitClue ('we,' 'us,' or 'our') collects, uses, shares, and protects your data. By using FitClue, you agree to the practices described in this policy."
        },
        {
            title: "Data Collection",
            description: (
                <div>
                    <p>FitClue collects the following categories of data:</p>
                    <ul className='list-unstyled'>
                        <li>
                            - Email Account Information: The email address you provide during account registration is stored in the platform's database (Appwrite).
                        </li>
                        <li>
                            - Local Storage Data: FitClue stores a unique user identifier, generated by Appwrite, in your browser's local storage to maintain session persistence and improve user experience. This data remains on your device and is used solely to manage sessions within the platform.
                        </li>
                        <li>
                            - Username: The username you choose is stored and may be visible to other users on the platform.
                        </li>
                        <li>
                            - Content Shared: This includes any text, comments, or links you post on the platform. Such content may remain visible to other users even after account deletion, unless it is removed or required to be deleted by law.
                        </li>
                        <li>
                            - Technical Data: IP addresses and usage logs are collected by Appwrite on our behalf and are used for security, debugging, and maintaining platform performance.
                        </li>
                    </ul>
                </div>
            )
        },
        {
            title: "Data Usage",
            description:
                <div>
                    <p>The data we collect is used to:</p>
                    <ul className='list-unstyled'>
                        <li>- Facilitate account creation.</li>
                        <li>- Display content and enable interactions within the platform.</li>
                        <li>
                            - Screen user-submitted content (including comments and links) for compliance with our <Link to='/tos' target='_blank'>Terms of Service</Link> and <Link to='/community-guidelines' target='_blank'>Community Guidelines</Link>.
                        </li>
                        <li>- Improve platform functionality and user experience.</li>
                    </ul>
                    <p>
                        Content that violates our policies is not submitted to the platform and is not stored.
                    </p>
                </div>
        },
        {
            title: "Data Sharing",
            description: (
                <div>
                    <p>
                        FitClue does not sell or rent your data to third parties. However, data may be shared in the following circumstances:
                    </p>
                    <ul className='list-unstyled'>
                        <li>
                            - Service Providers: We use Appwrite to provide backend infrastructure and database services. Appwrite processes and stores data (including IP addresses) on our behalf as part of providing the platform.
                        </li>
                        <li>
                            - AI-Powered Features: We use the Google Gemini API to review user-submitted content for compliance with our policies. When you submit content, it is sent to the API for analysis. Content flagged as violating our policies is not stored or published by FitClue. This process helps prevent harmful content from appearing on the platform while minimizing the data we retain. The handling of this data is governed by Google's policies.
                        </li>
                        <li>
                            - Legal Requirements: We may disclose data if required to do so by law or in response to valid legal requests.
                        </li>
                        <li>
                            - Platform Integrity: We may review data internally to investigate violations of our Terms of Service or to maintain the safety and integrity of the platform.
                        </li>
                    </ul>
                    <p>
                        Once data is shared with third-party providers, its handling is subject to their respective policies and practices.
                    </p>
                </div>
            )
        },
        {
            title: "Data Storage and Security",
            description:
                <div>
                    <p>
                        Your data is stored on servers managed by Appwrite. While we take reasonable steps to protect your information, FitClue is a personal project and does not implement advanced security measures such as end-to-end encryption or multi-factor authentication. You are encouraged to:
                    </p>
                    <ul className='list-unstyled'>
                        <li>- Use strong passwords for your account.</li>
                        <li>- Avoid sharing sensitive or personal information on the platform.</li>
                    </ul>
                </div>
        },
        {
            title: "User Rights",
            description:
                <div>
                    <p>
                        You have the right to:
                    </p>
                    <ul className='list-unstyled'>
                        <li>- Request correction of your data.</li>
                        <li>- Report privacy concerns or violations through the platform.</li>
                    </ul>
                </div>
        },
        {
            title: "Cookies and Tracking",
            description:
                <div>
                    <p>
                        FitClue uses cookies and similar technologies to support core functionality and improve user experience.
                    </p>
                    <ul className='list-unstyled'>
                        <li>
                            - Authentication Cookies: Cookies set by Appwrite are used to manage user login sessions and keep you authenticated while using the platform.
                        </li>
                        <li>
                            - Local Storage: FitClue stores a unique user identifier (generated by Appwrite) in your browser's local storage to maintain session persistence. This data remains on your device and is used only within the platform.
                        </li>
                        <li>
                            - Third-Party Content: FitClue embeds content from Instagram. These embedded posts may set cookies or collect data in accordance with Instagram's and Meta's privacy policies. FitClue does not control these cookies and does not access the data collected by them.
                        </li>
                    </ul>
                    <p>
                        FitClue does not use cookies or similar technologies for advertising or tracking you across other websites.
                    </p>
                </div>
        },
        {
            title: "Children's Privacy",
            description: `
      FitClue is not intended for individuals under the age of 18. We do not knowingly collect personal data from children. If we become aware that such data has been collected, it will be deleted promptly.
    `
        },
        {
            title: "Updates to This Policy",
            description: `
      This Privacy Policy may be updated periodically. You will be notified of changes through platform announcements. Continued use of FitClue after updates constitutes acceptance of the revised policy.
    `
        },
        {
            title: "Contact Information",
            description: `
      For questions or concerns about this Privacy Policy, please contact us at: FitClue@altmails.com.
    `
        }
    ];

    return { privacyPolicyData };
}

export default PrivacyData;