import { Link } from "react-router-dom";

const PrivacyData = () => {

    const privacyPolicyData = [
        {
            title: "Introduction",
            description: "This Privacy Policy outlines how FitClue ('we,' 'us,' or 'our') collects, uses, shares, and protects user data. By using FitClue, you agree to the practices described in this policy."
        },
        {
            title: "Data Collection",
            description: (
                <div>
                    FitClue collects the following categories of data:
                    <ul className='list-unstyled'>
                        <li>
                            - Email Account Information: The email address provided during account registration is securely stored in the platform's database (via Appwrite).
                        </li>
                        <li>
                            - Local Storage Data: FitClue stores a unique user identifier, generated by Appwrite, in the browser's local storage to maintain session persistence and improve user experience. This data is stored only in the user's browser and is used solely by FitClue to manage sessions within the platform. It is not shared with third parties or used for tracking outside FitClue.
                        </li>
                        <li>
                            - Username: The chosen username is stored and may be visible to other users on the platform.
                        </li>
                        <li>
                            - Content Shared: This includes any text, comments, or links posted by the user on the platform. Such content may remain visible to other users even after account deletion, unless it is manually removed or required to be deleted by law.
                        </li>
                        <li>
                            - Technical Data: IP addresses and usage logs are collected by Appwrite on behalf of FitClue and are used for security, debugging, and maintaining platform performance.
                        </li>
                    </ul>
                </div>
            )
        },
        {
            title: "Data Usage",
            description:
                <div>
                    The data we collect is used to:
                    <ul className='list-unstyled'>
                        <li>- Facilitate account creation.</li>
                        <li>- Display content and enable interactions within the platform.</li>
                        <li>- To help ensure a safe environment, we use automated tools to screen user-submitted content (including comments and links) for violations of our <Link to='/tos' target='_blank'>Terms of Service</Link> and <Link to='/community-guidelines' target='_blank'>Community Guidelines</Link>. If content is deemed to violate our policies, it is not submitted to the platform and is not stored by us. No record of the user or the attempted submission is retained.</li>
                        <li>- Improve platform functionality and user experience.</li>
                    </ul>
                </div>
        },
        {
            title: "Data Sharing",
            description: (
                <div>
                    FitClue does not sell or rent user data to third parties. However, data may be shared in the following circumstances:
                    <p>
                        Once data is shared with third-party providers, its handling is subject to their respective policies and practices.
                    </p>
                    <ul className='list-unstyled'>
                        <li>
                            - Service Providers: We rely on Appwrite to provide backend infrastructure and database services. Appwrite processes and stores user data (including IP addresses) on our behalf part of providing the platform.
                        </li>
                        <li>
                            <li>
                                - AI-Powered Features: We use the Google Gemini API to review user-submitted content for compliance with our policies. When you submit content, it is sent to the API for analysis. Content flagged as violating our policies is not stored or published by FitClue. This process helps prevent harmful content from appearing on the platform while minimizing the data we retain. The handling of this data is governed by Google's policies.
                            </li>
                        </li>
                        <li>
                            - Legal Requirements: We may disclose user data if required to do so by law or in response to valid legal requests.
                        </li>
                        <li>
                            - Platform Integrity: We may review user data internally to investigate violations of our Terms of Service or to maintain the safety and integrity of the platform.
                        </li>
                    </ul>
                </div>
            )
        },
        {
            title: "Data Storage and Security",
            description:
                <div>
                    Your data is stored on servers managed by Appwrite. While we strive to protect your information, FitClue is a personal project and does not implement advanced security measures such as end-to-end encryption or multi-factor authentication. Users are encouraged to:
                    <ul className='list-unstyled'>
                        <li>- Use strong passwords for their accounts.</li>
                        <li>- Avoid sharing sensitive or personal information on the platform. </li>
                    </ul>
                </div>
        },
        {
            title: "User Rights",
            description:
                <div>
                    Users have the right to:
                    <ul className='list-unstyled'>
                        <li>- Request correction of their data.</li>
                        <li>- Report privacy violations using the 'Privacy Violation' category in the Community Guidelines.</li>
                    </ul>
                </div>
        },
        {
            title: "Cookies and Tracking",
            description:
                <div>
                    FitClue uses cookies and similar technologies to support core functionality and improve user experience.
                    <ul className='list-unstyled'>
                        - Authentication Cookies: Cookies set by Appwrite are used to manage user login sessions and keep users authenticated while using the platform.

                        - Local Storage: FitClue stores a unique user identifier (generated by Appwrite) in the browser's local storage to maintain session persistence. This data remains on the user's device and is used only within the platform.

                        - Third-Party Content: FitClue embeds content from Instagram. These embedded posts may set cookies or collect data in accordance with Instagram's and Meta's privacy policies. FitClue does not control these cookies and does not access the data collected by them.
                    </ul>
                    FitClue does not use cookies or similar technologies for advertising or tracking users across other websites.
                </div>
        },
        {
            title: "Children\'s Privacy",
            description: `
      FitClue is not intended for users under the age of 18. We do not knowingly collect personal data from children. If we become aware that such data has been collected, we will delete it promptly.
    `
        },
        {
            title: "Updates to This Policy",
            description: `
      This Privacy Policy may be updated periodically. Users will be notified of changes through platform announcements. Continued use of FitClue after updates constitutes acceptance of the revised policy.
    `
        },
        {
            title: "Contact Information",
            description: `
      For questions or concerns about this Privacy Policy, please contact us at: FitClue@altmails.com.
    `
        }
    ];

    return { privacyPolicyData };
}

export default PrivacyData;